### ISSUE TITLE
Can't Install python 3.9.16

### ISSUE THREAD

**Issue by SnoopyDevelops** [adang1345/PythonWindows#13] opened 2023-01-05 20:31 UTC
![image](https://user-images.githubusercontent.com/54778084/210874364-a0a23fe1-e55d-4ea8-8531-1e5a47ee9657.png)

**Comment by adang1345** [comment] 2023-01-05 22:52
I am unable to reproduce this problem. In my experience, this error usually means that you have an earlier broken installation of Python 3.9 or that you have an instance of Python 3.9 that was not uninstalled all the way. Try to remove Python 3.9 completely and reinstalling.

**Comment by SnoopyDevelops** [comment] 2023-01-05 23:56
This happens with python installer version of 3.9.15 and 3.9.16 when installing directly without previous installation.
After that, I tried to install python 3.9.14 and it was successful.
Then, upgrading into 3.9,16 showed same error.

**Comment by adang1345** [comment] 2023-01-06 02:01
I tried the following, and both were successful for me.
- Install 3.9.16 directly without a previous installation.
- Install 3.9.14 and then upgrade to 3.9.16.

Perhaps viewing the installation log will indicate why it's not working for you. If you go to `C:\Users\<user>\AppData\Local\Temp`, you should see a file with a name similar to `Python 3.9.16 (64-bit)_20230105205819.log`. Open that and see if it provides useful information.

**Comment by adang1345** [comment] 2023-02-08 21:50
I'm closing this issue. Feel free to re-open if you still need help resolving your problem.

**Closed by adang1345** 2023-02-08 21:50 UTC

**Comment by faryx** [comment] 2023-02-09 17:56
![image](https://user-images.githubusercontent.com/70784522/217897906-4ae7da23-7802-424e-af6d-23bddf04357e.png)
windows 11 support.

**Comment by SnoopyDevelops** [comment] 2023-06-10 03:41
I'm still having same problem with 3.9.17

**Comment by adang1345** [comment] 2023-06-10 04:03
Are you able to view the installation log?

**Comment by SnoopyDevelops** [comment] 2023-06-10 04:06
[Python 3.9.17 (64-bit)_20230609230301.log](https://github.com/adang1345/PythonWindows/files/11711474/Python.3.9.17.64-bit._20230609230301.log)

I took a look, but can't figure out what the issue is

**Comment by adang1345** [comment] 2023-06-10 17:42
My guess is that you have a corrupt registry, and I would suggest that you try method 2 or 5 at https://thegeekpage.com/the-feature-you-are-trying-to-use-in-on-a-network-resource-that-is-unavailable-in-windows-10-fix/.
